spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/Cars
    username: postgres
    password: 1234
security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/
auth0:
  audience: http://localhost:8080/api/v1
  domain: dev-0o5y36dt5g02buep.us.auth0.com