version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: Cars
    volumes:
      - mysql_data:/var/lib/mysql

  your-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Cars
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      auth0.audience: http://localhost:8080/api/v1
      auth0.domain: dev-0o5y36dt5g02buep.us.auth0.com

volumes:
  mysql_data:
